apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:node-proxier
      rolearn: arn:aws:iam::257821106339:role/qa-gtsk-uswest2-core-fargate-role
      username: system:node:{{SessionName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::257821106339:role/qa-gtsk-uswest2-core-build
      username: qa-gtsk-uswest2-core-build
      rolearn: arn:aws:iam::257821106339:role/qa-gtsk-uswest2-core-deploy
      username: qa-gtsk-uswest2-core-deploy
      rolearn: arn:aws:iam::257821106339:role/qa-gtsk-uswest2-core-eks-role
      username: qa-gtsk-uswest2-core-eks-role
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system